config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/apel/apel:
      branch: dev
      repo: https://github.com/apel/apel.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/apel/apel git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-persimmon-hound.sh
        container: qc.acc_ugly-amber-caiman
  QC.Doc:
    repos:
      github.com/apel/apel find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-celadon-bison.sh
        container: qc.doc_gimpy-cream-frog
      github.com/apel/apel git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-heliotrope-tang.sh
        container: qc.doc_gimpy-turquoise-bracke
      github.com/apel/apel markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-apricot-walrus.sh
        container: qc.doc_sleepy-chestnut-foxhound
  QC.Lic:
    repos:
      github.com/apel/apel licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-dandelion-olm.sh
        container: qc.lic_scaly-mauve-goat
  QC.Sec:
    repos:
      github.com/apel/apel bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-myrtle-whale.sh
        container: qc.sec_sleepy-mustard-fousek
  QC.Sty:
    repos:
      github.com/apel/apel flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-heliotrope-baboon.sh
        container: qc.sty_tacky-amethyst-ferret
  QC.Uni:
    repos:
      github.com/apel/apel pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-burgundy-pinscher.sh
        container: qc.uni_trippy-dandelion-lobster
  QC.Ver:
    repos:
      github.com/apel/apel get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-wheat-wolverine.sh
        container: qc.ver_baggy-dandelion-labradoodle
timeout: 5400
